# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70576c5ad4193dd617aa15de2fd58425518eff8547ac7f55f0096cbd927f96e90ef21b4c38392a23135a96a7fd5efbfef183e6766149cb7d0df7242ee86db195

test:
  secret_key_base: cd34e7f450fb90cca16c58f7a886f8298995c2a51b29743e42cfc577bfe1bcc74414f87a89806d734d0a1add30bfd3ba36df2d1ac979afae39e657185586d936

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
